trigger:
  batch: true
  branches:
    include:
      - "main"

variables:
- name: SolutionBaseName
  value: 'SFA.DAS.ApprenticeCommitments.Web'
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.34
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
