trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: SolutionBaseName
  value: 'SFA.DAS.ApprenticeCommitments.Web'
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'

pool:
  name: 'DAS - Continuous Integration Agents'
  demands: LATEST_DOTNET_VERSION -equals 3.1

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.10
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
