trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
- name: SolutionBaseName
  value: SFA.DAS.ApprenticeCommitments.Web
- name: BuildPlatform
  value : any cpu
- name: BuildConfiguration
  value: release

pool:
  name: DAS - Continuous Integration
  workspace:
    clean: all

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)